version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  tileserver:
    image: klokantech/tileserver-gl
    restart: always
    ports:
      - "9000:80"
    volumes:
      - ./tiles:/data

volumes:
  pgdata:
