#!/bin/bash
if [[ ! -d "env" ]]; then
	echo "run setup script (\"./setup\") first!"
	exit 1
fi

PG_PASS="setup_out/burd_db.pgpass"

# shellcheck source=/dev/null
source env/bin/activate

$PG_PASS python3 -m NestUi
deactivate